### PR TITLE
Fix utils to not require `TENANT_USE_ASGIREF` to be defined in the host django project

### LINKED ISSUE #205: Release 4.1.0 overwrote 4.0.0 wheel
It looks like the publication of the 4.1.0 release overwrote the 4.0.0 wheels on pypi.

image

The broken 4.0.0 wheel now produces this error:

```python
AttributeError: 'Settings' object has no attribute 'TENANT_USE_ASGIREF'
```

The asgiref support should not be part of 4.0.0 but only of 4.1.0.

### PR DESCRIPTION
**Pull request by ekampf**
Most projects using `django-multitenant` wont have `TENANT_USE_ASGIREF` defined as its a new feature. 
They also shouldnt be required to add it... should just be treated as `False` if missing.

This is an issue that was introduced by #198 

Note that this will also resolve #205 issues

### CODE REVIEW

**Comment by ekampf** [comment]
FYI @gurkanindibay this is an issue thats breaking everyone installing the new 4.1.0

**Comment by gurkanindibay** [comment]
> FYI @gurkanindibay this is an issue thats breaking everyone installing the new 4.1.0

@ekampf Thanks for the heads up. I'm checking

**Comment by gurkanindibay** [comment]
@ekampf could you check the errors

Thanks

**Comment by ekampf** [comment]
@microsoft-github-policy-service agree [company="twingate"]

**Comment by ekampf** [comment]
@microsoft-github-policy-service agree

**Comment by ekampf** [comment]
@microsoft-github-policy-service agree company="twingate"

**Comment by ekampf** [comment]
@gurkanindibay tests fixed

**Review by gurkanindibay — APPROVED** [review]

**Comment by gurkanindibay** [comment]
@ekampf I released v4.1.1 with your PR. Could you check?
Thanks

**Comment by ekampf** [comment]
@gurkanindibay thanks!   confirming it works

**Comment by gurkanindibay** [comment]
@ekampf thanks for your contribution.
